---
title: "Aquatic Resource Trade in Species (ARTIS) Methods"
header-includes:
  - \usepackage{floatrow}
  - \floatplacement{figure}{H}
  - \hypersetup{linktocpage, colorlinks = true, linkcolor = blue}
  - \usepackage{draftwatermark}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \renewcommand{\headrulewidth}{0pt}
  - \rfoot{\thepage}
output: 
  bookdown::pdf_document2:
    fig_caption: yes
    toc: yes
    toc_depth: 2
---

# Overview

In order to estimate the seafood species trade network, we compiled and aligned diverse data on fishery and aquaculture production, live weight conversion factors, bilateral global trade, and nutrient content. While our data comes from open/published sources, its compilation was an immense task. Its comprehensive scale spans the globe and encompasses decades of changes in country and species names and seafood product forms. Over 4000 live weight conversion factors were compiled and matched to 2000+ farmed and wild capture aquatic species which in turn were matched to 900+ traded seafood product descriptions. This is then  aligned with the nutritional data that has been compiled across all aquatic seafood taxa for over 300 micronutrients. Our estimation of species trade flows occurs in two steps. First, we take a mass balance approach, where each country’s seafood exports must equal the domestic production, plus imports, minus domestic consumption, after accounting for processing losses. For each country, we estimate the proportion of seafood production going into each possible commodity, the proportion of each imported commodity processed and exported, and the domestic consumption of each commodity. We then use these estimates with bilateral trade data to solve for the global species flows. This approach substantially improves upon previous efforts by estimating species-level trade, covering all production environments (marine and freshwater) and production methods (farmed and wild caught), and including the processing and export of imported products. 

# Data 

## Production

Seafood production comes from the Food and Agriculture Organization (FAO), which provides national capture and aquaculture production (FAO 2020). The Food and Agriculture Organization provides annual capture and aquaculture production data for around 240 countries, territories or land areas from 1950 to 2019 in the FAO FishStatJ database. The FAO data reports production in tonnes (live weight equivalent) of around 550 farmed and 1600 wild capture species and species groups  classified by International Standard Statistical Classification of Aquatic Animals and Plants (ISSCAAP). FAO production data consists primarily of official national statistics, with some verifiable supplemental information from academic reviews, consultant reports, and other specialist literature. Data reported by nations are checked by the FAO for consistency and questionable values are verified with the reporting offices. When countries fail to report production, FAO uses past values to estimate production. For the purposes of this analysis, we do not distinguish between nationally-reported and FAO estimated values.

According to the Coordinating Working Party on Fishery Statistics, catch and landings should be assigned to the country of the flag flown by the fishing vessel irrespective of the location of the fishing. This means that production resulting from a country operating a fishing vessel in a foreign (host) country's territory should be recorded in the national statistics of the foreign fishing vessel. However, if the vessel is chartered by a company based in the home country or the vessel is fishing for the country under a joint venture contract or similar agreement and the operation is integral to the economy of the host country, this does not apply.

## Bilateral trade data

We use the CEPII BACI world trade database, which is a reconciled version of the UN Comtrade database (Gaulier and Zignago 2010). Trade data are reported to the UN by both importers and exporters following the Harmonized System (HS) codes. The HS trade code system organizes traded goods into a hierarchy, with the highest level represented by two digit codes (e.g., Chapter 03 covers "Fish and Crustaceans, Molluscs and Other Aquatic Invertebrates"), which are broken down into 4-digit headings (e.g., heading 0301 covers "Live fish"), which are then subdivided into 6-digit subheadings (e.g., subheading 030111 covers "Live ornamental freshwater fish"). National statistics offices may further subdivide HS codes into 7- to 12-digit codes but since these are not standard across countries, the HS 6-digit codes are the most highly resolved trade codes available globally. HS codes are administered by the World Customs Organization, which updates the codes every five years. HS versions can be used from their introduction through the present, meaning that the HS 2002 version provides a time series of trade from 2002 to the present whereas the HS 2017 version only provides a time series back to 2017. Notably, HS version 2012 included major revisions to the HS codes relevant to fisheries and aquaculture products. Changes in individual trade codes can be viewed [here](https://hstracker.wto.org/).

CEPII reconciles discrepancies by first removing transportation costs and using a weighting scheme based on each country's reporting reliability to average discrepancies in reported mirror flows, which occur in around 35% of observations (for all traded commodities). The BACI data focuses on trade flows between individual countries since 1994 and therefore drops flows within some groups of countries (e.g. Belgium-Luxembourg) to ensure consistent geographies. The resulting data set covers trade for over 200 countries and 5,000 products. Further details on the BACI data set are available in Gaulier and Zignago (2010). 

## Live weight conversions

Global trade data is reported in terms of the product weight. In order to convert from product weight (i.e., net weight) to the live weight equivalent, a live weight conversion factor must be applied for each HS code. Live weight conversion factors are sourced from the European Market Observatory for Fisheries and Aquaculture Products (EUMOFA) (EUMOFA 2019), along with various national and international governmental report values. The EUMOFA data reports live weight conversion factors by CN-8 codes, so the mean of the live weight conversion factors falling within each HS 6-digit code are used here. The EUMOFA data assigns products primarily destined for industrial purposes (e.g., fish meal and fish oil), co-products (e.g., caviar) and live trade a value of zero. In this analysis, co-products retained a live weight conversion factor value of zero to avoid double counting, but live animal trade was assigned a live weight conversion factor of 1 and fish meal and fish oil was assigned an average value of 2.98 (Jackson 2009). Data compiled from reports were categorized into taxa types (mollusks, crustaceans, fishes, and other aquatic invertebrates), FAO ISSCAAP groups, species or taxon name, type of processing, and country of processing. 

The live weight conversion factors applied to trade data introduce a potential source of uncertainty and error due to the fact that uncertainty in conversion factors is not reported and a single live weight conversion factor is presented per code, regardless of the species or region of origin. This is a limitation given that there is known geographical variation in live weight conversion factors due to differences in processing technology. Despite this limitation, the EUMOFA data offers better documentation and alignment with HS commodity codes than other live weight conversion factor data sources (Gephart et al. 2019) and is updated annually, providing documentation for changes in live weight conversion factors. Additionally, by supplementing the EUMOFA data  with the other reported values we can better capture specific species processing into various product forms and some regional variability. 

All conversion factors were reported as live weight to product weight ratios.Estimated means and standard deviations for the live weight conversion factors are provided in XX. These conversion factors were mapped onto possible species to commodity or commodity to commodity conversions (described in section XX). For commodity to commodity conversions, we estimate the conversion factors (i.e., processing loss rate) as the additional mass lost when converting from the live weight to the original product form relative to converting from live weight to the processed product form. This can be calculated as the live weight conversion factor for the original product form divided by the live weight factor for the processed product form. We assume that mass cannot be gained through processing and set a minimum of 1% mass loss for processing conversion factors. Products which are not processed for export (i.e., are retained for domestic consumption) receive a value of -1 to account for them as consumption rather than export. 

# Seafood production and commodity conversion

For each country, we estimate the proportion of each species going into each commodity and the proportion of each imported commodity processed into each other commodity for export. Each species can only be converted into a subset of the commodities. For example, Atlantic salmon, *Salmo salar*, can be converted into whole frozen salmon or frozen salmon fillets, but cannot be converted to a frozen tilapia fillet. Similarly, each commodity can only be converted to a subset of other commodities through processing. For example, whole frozen salmon can be processed into frozen salmon fillets, but not vice versa and neither salmon commodity can be converted to a tilapia commodity through processing. Defining possible conversions restricts the solution space to realistic results and improves estimation by substantially reducing the number of unknowns. We describe this assignment process below. 

## Taxonomic group to commodity assignment

The species production to commodity assignment is a many-to-many matching problem, wherein one commodity can consist of multiple species and one species can be converted to multiple commodities. To identify predominantly marine, capture-sourced HS codes, it is necessary to identify the species falling within each code. All taxonomic groups reported in the FAO production data were therefore matched to the HS 6-digit codes based on the code descriptions and hierarchy. We use the HS code descriptions to identify possible species to commodity conversion.

The first matching step required dividing all taxonomic groups into the broad commodity groups at the 4-digit level (fish, crustaceans, molluscs and aquatic invertebrates). Within each of these groups, taxonomic groups were matched based on 6 types of matching categories:

1. Explicit taxa match - Matched based on taxonomic information provided in the code description
2. NEC match - All remaining unmatched species within the 4-digit level are assigned to the “not elsewhere considered” (NEC) code
3. NEC by taxa match - When a code description signifies an NEC group, but limits this based on a taxonomic category (e.g., Salmonidae, N.E.C.), the NEC grouping occurs at this level, rather than the broad NEC match
4. Broad commodity match - Only the broad taxonomic groups inform this assignment since no further taxonomic information is provided
5. Aquarium trade match - Assigned to ornamental species trade based on species found in the aquarium/ornamental trade (REF)
6. Fish meal and fish oil match - Assigned to fish meal and fish oil codes based on reported species used in fish oils and fish meals (REF)

All species are matched to at least one HS code. 

## Commodity to commodity processing assignment

As with the species to commodity assignment, the commodity-to-commodity assignment is a many-to-many data problem. Here, one commodity can be processed into multiple other commodities (i.e., frozen salmon can be processed into salmon fillets or canned salmon), which also means one commodity could have come from multiple other commodities. To create these assignments, we established rules for which product transformations are technically possible. First, a product could not transfer outside of its broad commodity group (e.g., fish, crustaceans, mollusc, aquatic invertebrate). Second, where a more refined species or species group was given (e.g., tunas, salmons, etc.) a product cannot be transformed outside that group. Third, products are classified in terms of their state (e.g., alive, fresh, frozen, etc.) and presentation (e.g., e.g., whole, filleted, salted/dried/preserved meats, reductions such as fish meal and fish oil, etc.) and cannot be converted into less processed forms (e.g., frozen salmon fillets cannot turn into fresh salmon fillets, and frozen salmon fillets cannot turn into a frozen whole salmon). We ensure all commodities match to at least one taxon and all taxa match at least one commodity.

## Country standardization

Describe country standardization and point to country list, with territories included. Country list based on Comtrade documentation (https://comtrade.un.org/db/mr/rfReportersList.aspx)

# Network Estimation

Estimating species bilateral trade flows occurs in two steps: first, solving the national production-trade mass balance, and second, converting reported commodity trade flow estimates to species trade flow estimates based on the estimated species mix going into each commodity.

## National mass-balance

We start with the fact that exports must equal production and imports, minus consumption. Since exports are reported as commodities, we solve this mass balance problem in terms of commodities. Production data are reported for each species, so we estimate the elements of a matrix that represents the proportion of production going into each commodity. Since an imported commodity can be processed and exported as a different commodity, we also estimate the proportion of each import being converted into a different commodity (possible conversions described in section XX). Then for a given country,

$$e=V_1 \circ X \cdot p+V_2 \circ W \cdot g - c + \epsilon$$

If $n$ is the number of species and $m$ is the number of commodities, then: $V_1$ is a sparse ($m$ x $n$) matrix with product conversion factors corresponding to the unknowns in $X$; $X$ is a sparse ($m$ x $n$) matrix of the proportion of each species in each commodity; $p$ is a vector of domestic species production ($n$ x $1$); $V_2$ is a sparse ($m$ x $m$) matrix with product conversion factors corresponding to the entries of $W$; $W$ is a ($m$ x $m$) matrix of the processed imported commodities; g be a vector of imports ($m$ x $1$), $c$ is a vector of domestic consumption ($m$ x $1$), and; $\epsilon$ is a vector of error terms ($m$ x $1$). 

We compiled reported values for $V_1$, $V_2$, $e$, $p$ and $g$, and estimate the entries of $X$, $W$, $c$, and $\epsilon$. We first converted this problem to a system of linear equations. Using the property that $vec(ABC) = (C^T \otimes A)vec(B)$, we can create $A_b = (y^T \otimes D_m)D_V$, where $D_m$ is a diagonal matrix of ones, with dimension $m$ and $D_V$ is a diagonal matrix with the elements of $vec(V)$. The vector of unknowns is then $x_b = vec(Z)$. We then solve this system of equations with a quadratic optimization solver such that the mass balance equalities are satisfied, trade codes with higher species resolution in $X$ are filled first, the elements of $X$ are otherwise as even as possible (i.e., we assume an even distribution of production among commodities unless the data suggests otherwise), the elements of $W$ are as uneven as possible (i.e., we assume imported products are for domestic consumption unless the data suggests otherwise), and that $\epsilon$ is as small as possible (i.e., minimize the error). 

Positive error terms represent situations where reported production and imports cannot explain exports. This can occur due to under- or un-reported production or imports, over reporting of exports, errors in the live weight conversion factors, or inconsistencies in the year production and trade are attributed to.

We solve the mass-balance problem for each country-year-HS version combination using the *Python* package "solve_qp." The estimated species mixes in national production ($X$), proportion of imports processed for export (off-diagonal values of $W$) and the error term ($\epsilon$) are passed to the next stage of the analysis.

## Converting the product trade network to a species trade network

###______________________________________________________________________________________###
Old text
To convert reported bilateral trade of seafood products to species trade flows, we first identify the mix of species going into each trade code. To do this, we first must reweight $X$ so it represents the proportion of each species in a given code rather than the proportion of production of a species going into each product form. To do this, we take each country's estimated $X$, multiply by  production, and divide by the column sums. 

Next, we calculate the proportion of exports sourced from national production, imported and processed products, and from an unknown source (i.e., the error term). Since the mix of these sources cannot be derived from the mass balance equation alone, we calculate a range for the sourcing following Asche et al. (2022). To calculate the maximum exports from domestic production,  We apply the national reweighted $X$ to the exports from national production and the reweighted $X$ of trade partners (weighted based on import volume of each trade code) to import-sourced exports. Since the exports are of an unknown origin, we assign the most resolved common taxonomic name for the species falling within the code to the exports derived from the error term. 
###______________________________________________________________________________________###

To convert bilateral trade data expressed as commodities into species flows, we must trace flows back to their source country to link the commodities with the appropriate species mix. To do this, we draw from multi-regional input-output methods and first construct a flow matrix $F$, with sectors representing all country-commodity combinations and the origin ("from") sector on the row and destination ("to") sector on the column. To construct $F$, we multiply the estimated conversion of products for each country $i$ ($W_i$) element wise by the vector of imports by country-commodity combination, expressed as live weight equivalents. This then represents the bilateral flow of product entering each country and remaining in its current form and being processed into a new form according to the appropriate estimated national $W$ matrix. 

Our final demand vector is comprised of domestic production of each commodity ($X_i p_i$) plus imports of each commodity expressed as the final product form ($W_i g$) plus the estimated error export quantity ($\epsilon$). 

## Analysis implementation

- Add details about implementation in R and on Zorro

## Network post-estimation processing

- Removal of small trade flows
- Dealing with different HS versions

# Estimated network checks

## Comparison of total trade volumes to other reported values

## Comparison of trade patterns with simplified versions of the model

## Agreement across HS versions

## Comparison of production and trade data

# Conversion to nutrient flows

Questions for Daniel: 
- I heard AFCD has a species ID number - what system is used? 
- Key questions will be:
  - What product forms should we use? 
    - Start with muscle tissue but need to talk to Chris 
  - How should we aggregate up for genus, family, etc. level observations? 
    - 
  - Handling missing values
    - Fill in with a hierarchical approach - if no direct match, go with genus, etc. 
- Note: Initially, we just need nutrient flows for the live weight equivalents, but we could incorporate product forms later

# Planned future improvements

- Add economic realism
- Potentially incorporate more detailed national trade statistics
- Consider constructing matrix analogous to Xq for W that would push product transformations toward staying within a species group before using NEC codes to explain mass
- Add in FAO 2020 data - BACI data is already available and FAO data is also available, but we would need to test for structural chances in the data release before incorporating


# Integration with SAU

- Double check that producer corresponds to fishing entity
  - Yep!
- Marine has capture and mariculture, freshwater won't be available until the end of the year (she can provide a species list)
- Fishing entity, species, year, catch, gear, reporting status (FAO or reconstructed), sector, end use
- Deng will provide taxon table in addition to the catch data
- Send species list 
- Use a lineage approach for species groupings (prompt to look at peneus as well when they click peneus)
- Create species and country profile pages that link with SAU and Sea Life and Fish Base

# Outstanding issues

- Resolve whether to allow imports staying the same code to count toward exports or not (i.e., technical definition). This needs to be consistent across solve_country and make_snet
- Add trade flow confidence score

# Preliminary plots to add

- Network metrics over time by capture vs aquaculture
  - Average degree
  - Measure of node and edge distribution
  - Community detection of cliches over time (how does membership change)
  - Centrality 
  - Edge density
- 



